# Generated by Django 2.2 on 2021-06-19 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
