# Generated by Django 2.2 on 2021-06-19 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_app', '0004_auto_20210619_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='who_reviewed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='dojo_app.User'),
        ),
    ]
